name: flutter_multimedia
description: A Flutter multimedia project for practical work.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  video_player: ^2.5.1
  audioplayers: ^5.2.1
  location: ^7.0.0
  photo_view: ^0.15.0
  uuid: ^3.0.7
  file_picker: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/media/